CREATE TABLE signups (
    message_id BIGINT UNSIGNED PRIMARY KEY,
    name VARCHAR(32) NOT NULL
);

CREATE TABLE signup_categories (
    id SERIAL PRIMARY KEY,
    signup_id BIGINT UNSIGNED NOT NULL REFERENCES signups (id) ON DELETE CASCADE,

    name VARCHAR(32) NOT NULL,
    button_name VARCHAR(32) NOT NULL,
    max_slots TINYINT UNSIGNED,
    is_hoisted BOOL NOT NULL DEFAULT FALSE,
    is_anonymous BOOL NOT NULL DEFAULT FALSE,
    allows_hydra_slots BOOL NOT NULL DEFAULT FALSE,
    allows_single_slots BOOL NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE signup_slots (
    id SERIAL PRIMARY KEY,
    category_id INT NOT NULL REFERENCES signup_categories (id) ON DELETE CASCADE,

    name VARCHAR(32),

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE signup_users (
    id SERIAL PRIMARY KEY,
    slot_id INT NOT NULL REFERENCES signup_slots (id) ON DELETE CASCADE,
    user_id BIGINT UNSIGNED NOT NULL REFERENCES users (id) ON DELETE CASCADE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    UNIQUE KEY unq_slot_user (slot_id, user_id)
);
