CREATE TABLE servers (
  server_id BIGINT UNSIGNED PRIMARY KEY,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE server_flags (
  server_id BIGINT UNSIGNED NOT NULL,
  flag VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (server_id, flag),
  FOREIGN KEY (server_id) REFERENCES servers (server_id) ON DELETE CASCADE
);
