CREATE TABLE signups (
  message_id BIGINT UNSIGNED PRIMARY KEY,
  name VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE signup_categories (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  signup_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(32) NOT NULL,
  button_name VARCHAR(32),
  member_limit INT UNSIGNED,
  is_hoisted BOOLEAN NOT NULL DEFAULT FALSE,
  is_anonymous BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (signup_id) REFERENCES signups (message_id) ON DELETE CASCADE
);

CREATE TABLE signup_slots (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  category_id BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (category_id) REFERENCES signup_categories (id) ON DELETE CASCADE
);

CREATE TABLE signup_members (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  slot_id BIGINT UNSIGNED NOT NULL,
  member_id BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE (slot_id, member_id),
  FOREIGN KEY (slot_id) REFERENCES signup_slots (id) ON DELETE CASCADE,
  FOREIGN KEY (member_id) REFERENCES users (user_id) ON DELETE CASCADE
);
