CREATE TABLE signups (
  message_id BIGINT UNSIGNED PRIMARY KEY,
  name VARCHAR(32) NOT NULL,
  is_anonymous BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE signup_category (
  id BIGINT UNSIGNED PRIMARY KEY,
  name VARCHAR(32) NOT NULL,
  button_name VARCHAR(32),
  member_limit INT UNSIGNED,
  is_hoisted BOOLEAN NOT NULL DEFAULT FALSE,
  hydras_permitted BOOLEAN NOT NULL DEFAULT FALSE,
  hydras_forced BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE signup_slot (
  id BIGINT UNSIGNED PRIMARY KEY,
  category_id BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE signup_member (
  id BIGINT UNSIGNED PRIMARY KEY,
  slot_id BIGINT UNSIGNED NOT NULL,
  member_id BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
